server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true
    username: root
    password: zhou_19980228
    driver-class-name: com.mysql.jdbc.Driver